#spring.application.name=Sem9DZ
server:
  port: 8765



spring:
  application:
    name: api-getway-SpringDZ9

  cloud:
    gateway:
      routes:
        - id: Tasks
          uri: http://localhost:8081/
          predicates:
            - Path= /tasks/**
        - id: Notes
          uri: http://localhost:8082/
          predicates:
            - Path=/notes/**