#spring.application.name=Sem9DZ
server:
  port: 8765



spring:
  application:
    name: api-getway

  cloud:
    gateway:
      routes:
        - id: Tasks
          uri: http://localhost:8081/
          predicates:
            - Path=/tasksServer/**

        - id: Notes
          uri: http://localhost:8082/
          predicates:
            - Path=/noteServer/**